### PR TITLE
Different method of allowing additional suffixes

### PR DESCRIPTION
**Pull request by iamkoch**
Addition of additionalSuffixes to existing jshint options allows extension.

See updated README

### CODE REVIEW

**Comment by marcopeg** [comment]
+1, please add this PR to your project and push it to NPM!

**Comment by Munter** [comment]
What's with the changed indentation? I wouldn't merge this if it doesn't follow the convention of the repository

**Comment by marcopeg** [comment]
Hi Peter, I don't know why the guy has those problems with the indentation but the idea is good.

I see a real benefit of opening the list of extensions with a grunt task configuration option and it would be great also internally in brixo. You may want to apply the change yourself and publish the update.

Another really easy way is to provide the `defaultSuffix` as stand-alone module so it could be just rewired. (this last will take you no more than 30 secs to apply but is less elegant than the grunt task option version)

**Comment by iamkoch** [comment]
Sorry about that. PHPStorm making its mind up. Will sort once I'm home.

**Comment by iamkoch** [comment]
Plus it was ironically missed by jshint

**Comment by iamkoch** [comment]
I've sorted the spaces out.

**Comment by Munter** [comment]
Much nicer diff :)

**Pull request merged**
