### PR TITLE
remove react tools dependency

### PR DESCRIPTION
**Pull request by tparnell8**
react-tools has been depreciated :( use babel instead

### CODE REVIEW

**Comment by tillarnold** [comment]
Thanks! I'm currently at work, but I'll have a look at your changes and merge them later.

**Comment by tparnell8** [comment]
Thats fine man no hurry!!!

**Comment by tparnell8** [comment]
Awesomeness!!!!!!!!  \m/

**Comment by tillarnold** [comment]
Thanks a lot! I published Version 0.7.0 on npm.

**Pull request merged**
